# Generated by Django 6.0.6 on 2026-07-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trainingsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_key', models.CharField(max_length=50, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_si', models.CharField(blank=True, max_length=100)),
                ('n_min', models.FloatField()),
                ('n_max', models.FloatField()),
                ('p_min', models.FloatField()),
                ('p_max', models.FloatField()),
                ('k_min', models.FloatField()),
                ('k_max', models.FloatField()),
                ('ph_min', models.FloatField()),
                ('ph_max', models.FloatField()),
                ('moisture_min', models.FloatField()),
                ('moisture_max', models.FloatField()),
                ('water_frequency_days', models.IntegerField(default=3)),
                ('water_amount_mm', models.FloatField(default=25)),
                ('notes_en', models.TextField(blank=True)),
                ('notes_si', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
    ]
