# Generated by Django 6.0.6 on 2026-07-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_seed_cropguidelines'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=50)),
                ('name_si', models.CharField(blank=True, max_length=50)),
                ('price_per_kg', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('size_acres', models.FloatField(default=1.0)),
                ('crop_key', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CostEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_key', models.CharField(max_length=50)),
                ('size_acres', models.FloatField()),
                ('urea_kg', models.FloatField(default=0)),
                ('tsp_kg', models.FloatField(default=0)),
                ('mop_kg', models.FloatField(default=0)),
                ('urea_cost', models.FloatField(default=0)),
                ('tsp_cost', models.FloatField(default=0)),
                ('mop_cost', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_estimates', to='api.field')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reading',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='api.field'),
        ),
    ]
