# Generated by Django 6.0.6 on 2026-07-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_farm_field_device_id_field_latitude_field_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='auth_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='field',
            name='land_id',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='field',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
