# Generated by Django 6.0.6 on 2026-07-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_field_auth_token_field_land_id_field_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='field',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='field',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
