# Generated by Django 6.0.6 on 2026-07-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_staffaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='mode',
            field=models.CharField(default='existing', max_length=10),
        ),
    ]
