# Generated by Django 6.0.6 on 2026-07-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_field_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropguideline',
            name='price_per_kg',
            field=models.FloatField(default=0),
        ),
    ]
