# Generated by Django 6.0.6 on 2026-07-26 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cropguideline_price_per_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropEconomics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('yield_kg_per_acre', models.FloatField(default=0)),
                ('fertilizer_cost_per_acre', models.FloatField(default=0)),
                ('labor_cost_per_acre', models.FloatField(default=0)),
                ('seed_cost_per_acre', models.FloatField(default=0)),
                ('other_cost_per_acre', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['crop_key'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True)),
                ('name_en', models.CharField(max_length=80)),
                ('name_si', models.CharField(blank=True, max_length=80)),
                ('district', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_key', models.CharField(db_index=True, max_length=50)),
                ('price_per_kg', models.FloatField()),
                ('date', models.DateField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.market')),
            ],
            options={
                'ordering': ['-date', 'market__name_en'],
                'unique_together': {('market', 'crop_key', 'date')},
            },
        ),
    ]
